apiVersion: v1
kind: Service
metadata:
  name: farm-website
spec:
  selector:
    app: farm-website
  ports:
    - protocol: TCP
      port: 80        # Service port (cluster-internal)
      targetPort: 80   # Pod port
      nodePort: 30111  # External port you want to use
  type: NodePort